### ISSUE TITLE
Script pdf-info throwing exception after pdf-checker reports no error

### ISSUE THREAD

**Issue by tsalada** [p6-pdf/PDF-Class-p6#16]
After pdf-checker.raku --repair myFile.pdf ran and reported "completed with 0 warnings and 0 errors" I tried to display the file info with pdf-info.raku myFile.pdf and got the following error:

Type check failed in assignment to $box; expected List but got Positional[Numeric] (Positional[Numeric])
  in sub MAIN at /home/tsalada/rakudo-2020.06/share/perl6/site/resources/564D3C75174AAD1D6ACB041994069B712F6EA8B9 line 51
  in block <unit> at /home/tsalada/rakudo-2020.06/share/perl6/site/resources/564D3C75174AAD1D6ACB041994069B712F6EA8B9 line 7
  in sub MAIN at /home/tsalada/rakudo-2020.06/share/perl6/site/bin/pdf-info.raku line 3
  in block <unit> at /home/tsalada/rakudo-2020.06/share/perl6/site/bin/pdf-info.raku line 1

**Comment by dwarring** [comment]
@tsalada,
Sorry I missed this earlier. Should be fixed in PDF::Class 0.4.10.
