### ISSUE TITLE
Re-Installing PDF::Class Failed

### ISSUE THREAD

**Issue by tsalada** [p6-pdf/PDF-Class-p6#20]
After upgrading to the latest Rakudo (2021.08-01), re-installing PDF::Class failed. The error messages are in the attached file. 
 
[errMsg_Re-Installing_PDF_Class.txt](https://github.com/pdf-raku/PDF-Class-raku/files/7128735/errMsg_Re-Installing_PDF_Class.txt)

**Comment by dwarring** [comment]
It's latched on to an old PDF::Class version 0.4.4, when the current is 0.4.14.

Looking back at  0.4.4, I think I managed to confuse things, when I took `api` out of META6 2e518f0

edit: I think zef treats `:ver<0.4.4>:api<PDF1.7>` as satisfying dependency `:ver<0.14.4+>`

**Comment by dwarring** [comment]
0.4.4 is no longer indexed on CPAN, so I think zef must be picking up a stale release from its cache. Maybe try `$ rm ~/.zef/store/PDF-Class-*` before retrying `zef install PDF::Class`. To try to get it to install 0.4.14.

**Comment by dwarring** [comment]
More general recovery, if that doesn't work:
```
rm -r ~/.zef/store/PDF-*
zef uninstall PDF PDF::Content PDF::Grammar PDF::Class
zef install PDF::Class
```

**Comment by tsalada** [comment]
That last suggestion worked.
