### ISSUE TITLE
Dump when executing: "pdf-burst.raku --page=1 --save-as=t.pdf irrigation-plan.pdf"

### ISSUE THREAD

**Issue by tbrowder** [p6-pdf/PDF-Class-p6#22]
See the input file at:

[irrigation-plan.pdf](https://github.com/pdf-raku/PDF-Class-raku/files/11491949/irrigation-plan.pdf)

**Comment by dwarring** [comment]
Thanks Tom.

The cross reference table unusual. It's actually similar to [this SO question](https://stackoverflow.com/questions/76013029/eof-character-not-found]), which I commented on a few weeks ago. This also involved a PDF produced by the Microsoft print driver.

Seems the PDF cross reference indexing and parsing needs some changes to handle this.

**Comment by tbrowder** [comment]
Great that the problem is known. Any chance of a fix anytime soon?

I'm trying to modify that file to (1) scale it up and (2) add some text on top of the diagram to zoom in on the zone details of my new irrigation system I paid to have installed.  Thanks to your code I know I can do that!

**Comment by dwarring** [comment]
Hi Tom,
Should have a fix in the next few days.
In the interim you can run `pdf-rewriter.raku --repair` on the file to fix it.

I'll also add the `--repair` option to `pdf-burst.raku`.

**Comment by tbrowder** [comment]
On Tue, May 16, 2023 at 20:12 David Warring ***@***.***>
wrote:

> Hi Tom,
> Should have a fix in the next few days.
> In the interim you can run pdf-rewriter.raku --repair on the file to fix
> it.
>
Erg, that failed also.

-Tom

**Comment by dwarring** [comment]
OK, I'll get onto it over the next couple of days.

**Comment by dwarring** [comment]
@tbrowder please upgrade to latest PDF 0.5.17 and try again.

**Comment by tbrowder** [comment]
Great, working now! Thanks, David.
